/*
 * SPDX-FileCopyrightText: 2024 M5Stack Technology CO LTD
 *
 * SPDX-License-Identifier: MIT
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CoreLora

#include "ui.h"

#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t* ui_Screen1;
lv_obj_t* ui_Image1;
lv_obj_t* ui_Image2;
lv_obj_t* ui_Image3;
lv_obj_t* ui_Image4;
lv_obj_t* ui_Image5;
lv_obj_t* ui_Image6;
lv_obj_t* ui_Image7;
lv_obj_t* ui_Image8;
lv_obj_t* ui_Image9;
lv_obj_t* ui_Image10;
lv_obj_t* ui_Image11;
lv_obj_t* ui_Image12;
lv_obj_t* ui_Label1;
lv_obj_t* ui_Label3;
lv_obj_t* ui_Label4;
lv_obj_t* ui_Label5;
lv_obj_t* ui_Label6;
lv_obj_t* ui_Label7;
lv_obj_t* ui_Container2;
lv_obj_t* ui_Image14;
lv_obj_t* ui_Label8;
lv_obj_t* ui_Label9;
lv_obj_t* ui_Label10;
lv_obj_t* ui_Label11;
lv_obj_t* ui_Label12;
lv_obj_t* ui_Container3;
lv_obj_t* ui_Image15;
lv_obj_t* ui_Label17;
lv_obj_t* ui_Label2;
lv_obj_t* ui_Label13;
lv_obj_t* ui_Label14;
lv_obj_t* ui_Label15;
lv_obj_t* ui_Container4;
lv_obj_t* ui_Image16;
lv_obj_t* ui_Label18;
lv_obj_t* ui_Label19;
lv_obj_t* ui_Label20;
lv_obj_t* ui_Label21;
lv_obj_t* ui_Label22;
lv_obj_t* ui____initial_actions0;
const lv_img_dsc_t* ui_imgset_frame_[1]                    = {&ui_img_frame_3_png};
const lv_img_dsc_t* ui_imgset_lora_[1]                     = {&ui_img_lora_1_png};
const lv_img_dsc_t* ui_imgset_cm4_stack_logo[1]            = {&ui_img_cm4_stack_logo1_png};
const lv_img_dsc_t* ui_imgset_lorawan_gateway_on_coremp[1] = {&ui_img_lorawan_gateway_on_coremp135_png};
const lv_img_dsc_t* ui_imgset_vector_[3]    = {&ui_img_vector_1_png, &ui_img_vector_2_png, &ui_img_vector_3_png};
const lv_img_dsc_t* ui_imgset_1402240725[1] = {&ui_img_1858829983};
const lv_img_dsc_t* ui_imgset_rectangle_[2] = {&ui_img_rectangle_15_png, &ui_img_rectangle_15_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void) {
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t* dispp  = lv_disp_get_default();
    lv_theme_t* theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                              false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);

    lv_timer_create(get_system_info_cb, 3000, NULL);
    lv_timer_create(lora_enquene_msg_cb, 15000, NULL);
    connect_mqtt();
}
