// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: CoreLora

#ifndef _UI_TASK_H
#define _UI_TASK_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif
void get_system_info_cb(lv_timer_t *tmr);
void lora_enquene_msg_cb(lv_timer_t *tmr);
void connect_mqtt();
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
