// Layer Declaration header
//
// This file is auto-generated by cmake, don't edit it.

#include "layer/absval.h"
namespace ncnn { DEFINE_LAYER_CREATOR(AbsVal) }
#include "layer/arm/absval_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(AbsVal_arm) }
#include "layer/batchnorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BatchNorm) }
#include "layer/arm/batchnorm_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BatchNorm_arm) }
#include "layer/bias.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Bias) }
#include "layer/arm/bias_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Bias_arm) }
#include "layer/bnll.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BNLL) }
#include "layer/concat.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Concat) }
#include "layer/arm/concat_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Concat_arm) }
#include "layer/convolution.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution) }
#include "layer/arm/convolution_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution_arm) }
#include "layer/crop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Crop) }
#include "layer/arm/crop_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Crop_arm) }
#include "layer/deconvolution.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution) }
#include "layer/arm/deconvolution_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution_arm) }
#include "layer/dropout.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dropout) }
#include "layer/arm/dropout_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dropout_arm) }
#include "layer/eltwise.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Eltwise) }
#include "layer/arm/eltwise_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Eltwise_arm) }
#include "layer/elu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ELU) }
#include "layer/embed.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Embed) }
#include "layer/exp.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Exp) }
#include "layer/flatten.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Flatten) }
#include "layer/arm/flatten_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Flatten_arm) }
#include "layer/innerproduct.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InnerProduct) }
#include "layer/arm/innerproduct_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InnerProduct_arm) }
#include "layer/input.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Input) }
#include "layer/log.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Log) }
#include "layer/lrn.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LRN) }
#include "layer/arm/lrn_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LRN_arm) }
#include "layer/memorydata.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MemoryData) }
#include "layer/mvn.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MVN) }
#include "layer/pooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling) }
#include "layer/arm/pooling_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling_arm) }
#include "layer/power.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Power) }
#include "layer/prelu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PReLU) }
#include "layer/arm/prelu_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PReLU_arm) }
#include "layer/proposal.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Proposal) }
#include "layer/reduction.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reduction) }
#include "layer/relu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ReLU) }
#include "layer/arm/relu_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ReLU_arm) }
#include "layer/reshape.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reshape) }
#include "layer/arm/reshape_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reshape_arm) }
#include "layer/roipooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ROIPooling) }
#include "layer/scale.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Scale) }
#include "layer/arm/scale_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Scale_arm) }
#include "layer/sigmoid.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Sigmoid) }
#include "layer/arm/sigmoid_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Sigmoid_arm) }
#include "layer/slice.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Slice) }
#include "layer/arm/slice_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Slice_arm) }
#include "layer/softmax.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Softmax) }
#include "layer/arm/softmax_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Softmax_arm) }
#include "layer/split.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Split) }
#include "layer/tanh.h"
namespace ncnn { DEFINE_LAYER_CREATOR(TanH) }
#include "layer/arm/tanh_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(TanH_arm) }
#include "layer/threshold.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Threshold) }
#include "layer/tile.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Tile) }
#include "layer/rnn.h"
namespace ncnn { DEFINE_LAYER_CREATOR(RNN) }
#include "layer/arm/rnn_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(RNN_arm) }
#include "layer/lstm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LSTM) }
#include "layer/arm/lstm_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LSTM_arm) }
#include "layer/binaryop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BinaryOp) }
#include "layer/arm/binaryop_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(BinaryOp_arm) }
#include "layer/unaryop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(UnaryOp) }
#include "layer/arm/unaryop_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(UnaryOp_arm) }
#include "layer/convolutiondepthwise.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise) }
#include "layer/arm/convolutiondepthwise_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise_arm) }
#include "layer/padding.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Padding) }
#include "layer/arm/padding_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Padding_arm) }
#include "layer/squeeze.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Squeeze) }
#include "layer/expanddims.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ExpandDims) }
#include "layer/normalize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Normalize) }
#include "layer/permute.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Permute) }
#include "layer/priorbox.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PriorBox) }
#include "layer/detectionoutput.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DetectionOutput) }
#include "layer/interp.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Interp) }
#include "layer/arm/interp_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Interp_arm) }
#include "layer/deconvolutiondepthwise.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise) }
#include "layer/arm/deconvolutiondepthwise_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise_arm) }
#include "layer/shufflechannel.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ShuffleChannel) }
#include "layer/arm/shufflechannel_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ShuffleChannel_arm) }
#include "layer/instancenorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InstanceNorm) }
#include "layer/arm/instancenorm_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(InstanceNorm_arm) }
#include "layer/clip.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Clip) }
#include "layer/arm/clip_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Clip_arm) }
#include "layer/reorg.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Reorg) }
#include "layer/yolodetectionoutput.h"
namespace ncnn { DEFINE_LAYER_CREATOR(YoloDetectionOutput) }
#include "layer/quantize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Quantize) }
#include "layer/arm/quantize_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Quantize_arm) }
#include "layer/dequantize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dequantize) }
#include "layer/arm/dequantize_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Dequantize_arm) }
#include "layer/yolov3detectionoutput.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Yolov3DetectionOutput) }
#include "layer/psroipooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PSROIPooling) }
#include "layer/roialign.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ROIAlign) }
#include "layer/packing.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Packing) }
#include "layer/arm/packing_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Packing_arm) }
#include "layer/requantize.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Requantize) }
#include "layer/arm/requantize_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Requantize_arm) }
#include "layer/cast.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Cast) }
#include "layer/arm/cast_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Cast_arm) }
#include "layer/hardsigmoid.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSigmoid) }
#include "layer/arm/hardsigmoid_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSigmoid_arm) }
#include "layer/selu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(SELU) }
#include "layer/arm/selu_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(SELU_arm) }
#include "layer/hardswish.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSwish) }
#include "layer/arm/hardswish_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(HardSwish_arm) }
#include "layer/noop.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Noop) }
#include "layer/pixelshuffle.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PixelShuffle) }
#include "layer/arm/pixelshuffle_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(PixelShuffle_arm) }
#include "layer/deepcopy.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeepCopy) }
#include "layer/mish.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Mish) }
#include "layer/arm/mish_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Mish_arm) }
#include "layer/statisticspooling.h"
namespace ncnn { DEFINE_LAYER_CREATOR(StatisticsPooling) }
#include "layer/swish.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Swish) }
#include "layer/arm/swish_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Swish_arm) }
#include "layer/gemm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Gemm) }
#include "layer/arm/gemm_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Gemm_arm) }
#include "layer/groupnorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GroupNorm) }
#include "layer/layernorm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(LayerNorm) }
#include "layer/softplus.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Softplus) }
#include "layer/gru.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GRU) }
#include "layer/arm/gru_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GRU_arm) }
#include "layer/multiheadattention.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MultiHeadAttention) }
#include "layer/arm/multiheadattention_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MultiHeadAttention_arm) }
#include "layer/gelu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GELU) }
#include "layer/arm/gelu_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GELU_arm) }
#include "layer/convolution1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution1D) }
#include "layer/arm/convolution1d_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution1D_arm) }
#include "layer/pooling1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling1D) }
#include "layer/convolutiondepthwise1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise1D) }
#include "layer/convolution3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Convolution3D) }
#include "layer/convolutiondepthwise3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(ConvolutionDepthWise3D) }
#include "layer/pooling3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Pooling3D) }
#include "layer/matmul.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MatMul) }
#include "layer/arm/matmul_arm.h"
namespace ncnn { DEFINE_LAYER_CREATOR(MatMul_arm) }
#include "layer/deconvolution1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution1D) }
#include "layer/deconvolutiondepthwise1d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise1D) }
#include "layer/deconvolution3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Deconvolution3D) }
#include "layer/deconvolutiondepthwise3d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeconvolutionDepthWise3D) }
#include "layer/einsum.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Einsum) }
#include "layer/deformableconv2d.h"
namespace ncnn { DEFINE_LAYER_CREATOR(DeformableConv2D) }
#include "layer/glu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GLU) }
#include "layer/fold.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Fold) }
#include "layer/unfold.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Unfold) }
#include "layer/gridsample.h"
namespace ncnn { DEFINE_LAYER_CREATOR(GridSample) }
#include "layer/cumulativesum.h"
namespace ncnn { DEFINE_LAYER_CREATOR(CumulativeSum) }
#include "layer/copyto.h"
namespace ncnn { DEFINE_LAYER_CREATOR(CopyTo) }
#include "layer/erf.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Erf) }
#include "layer/diag.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Diag) }
#include "layer/celu.h"
namespace ncnn { DEFINE_LAYER_CREATOR(CELU) }
#include "layer/shrink.h"
namespace ncnn { DEFINE_LAYER_CREATOR(Shrink) }

