# component/SConscript
Import("env")
import os

with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())


if "CONFIG_NNG_ENABLED" in os.environ:
    check_component('nng')
    ext_compile_script = str(AFile("../../github_source/component_configs/{}-nng-{}-SConstruct.py".format(env['GCC_DUMPMACHINE'], env['GIT_REPO_LISTS']['nng']['commit'])))
    if not os.path.exists(ext_compile_script):
        ext_compile_script = str(AFile("../../github_source/component_configs/gcc-nng-{}-SConstruct.py".format(env['GIT_REPO_LISTS']['nng']['commit'])))

    if os.path.exists(ext_compile_script):
        with open(ext_compile_script) as f:
            exec(f.read())
