CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"
# CONFIG_COMPONENT1_ENABLED=y
CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
CONFIG_TOMMATH_ENABLED=y
CONFIG_TOMMATH_DYNAMIC=y