// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_start_ui
/*
* SPDX-FileCopyrightText: 2024 M5Stack Technology CO LTD
*
* SPDX-License-Identifier: MIT
*/
#include "../ui.h"

static void anim_x_cb(void *obj, int32_t v) {
    lv_obj_set_x(obj, v);
    //   lv_obj_set_x(obj, v);
    lv_obj_set_x(ui_Image[28], v + 320);
}

// void animate_move_y(lv_obj_t* obj,lv_coord_t y_start, lv_coord_t y_offset,
// uint16_t duration) {
static void animate_move_x(lv_obj_t *obj, int32_t start_x, int32_t end_x,
                           uint32_t duration) {
    lv_anim_t a;
    lv_anim_init(&a);
    lv_anim_set_var(&a, obj);
    lv_anim_set_values(&a, start_x, end_x);
    lv_anim_set_time(&a, duration);
    lv_anim_set_exec_cb(&a, anim_x_cb);
    lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
    lv_anim_start(&a);
}

#define absolute_x_val(val) val - lv_obj_get_x(ui_Tileview1)
#define absolute_y_val(val) val - lv_obj_get_y(ui_Tileview1)

void ui_Screen1_screen_init(void) {
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);

    // cpu
    ui_Image[0] = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image[0], &ui_img_1636868526);
    lv_obj_set_width(ui_Image[0], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[0], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[0], 0);
    lv_obj_set_y(ui_Image[0], 0);
    lv_obj_add_flag(ui_Image[0], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[0], LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_align(ui_Image[0], LV_ALIGN_TOP_LEFT);

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label2, -119);
    lv_obj_set_y(ui_Label2, -108);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "100%");

    // ram
    ui_Image[1] = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image[1], &ui_img_114329946);
    lv_obj_set_width(ui_Image[1], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[1], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[1], 62);
    lv_obj_set_y(ui_Image[1], 1);
    lv_obj_add_flag(ui_Image[1], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[1], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label3, -56);
    lv_obj_set_y(ui_Label3, -108);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "100%");

    // 时钟
    ui_Image[2] = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image[2], &mingcute_time_line);
    lv_obj_set_width(ui_Image[2], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[2], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[2], 233);
    lv_obj_set_y(ui_Image[2], 1);
    lv_obj_add_flag(ui_Image[2], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[2], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label1, 127);
    lv_obj_set_y(ui_Label1, -108);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "23:58:58");

    // 电池
    ui_Image[29] = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image[29], &battery2);
    lv_obj_set_width(ui_Image[29], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[29], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[29], 27);
    lv_obj_set_y(ui_Image[29], -108);
    lv_obj_set_align(ui_Image[29], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[29], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[29], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label22 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label22, 53);
    lv_obj_set_y(ui_Label22, -108);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "null");

    // 温度
    ui_Image[2] = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image[2], &Vector);
    lv_obj_set_width(ui_Image[2], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[2], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[2], 126);
    lv_obj_set_y(ui_Image[2], 1);
    lv_obj_add_flag(ui_Image[2], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[2], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Label21 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Label21, -3);
    lv_obj_set_y(ui_Label21, -108);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "100°C");

    ui_Tileview1 = lv_tileview_create(ui_Screen1);
    lv_obj_set_scrollbar_mode(ui_Tileview1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_width(ui_Tileview1, 320);
    lv_obj_set_height(ui_Tileview1, 196);
    lv_obj_set_x(ui_Tileview1, 0);
    lv_obj_set_y(ui_Tileview1, 44);
    lv_obj_set_align(ui_Tileview1, LV_ALIGN_TOP_LEFT);

    int TabPage_cout         = 0;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Image[3] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_Image[3], &Frame_2);
    lv_obj_set_width(ui_Image[3], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[3], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[3], absolute_x_val(47));
    lv_obj_set_y(ui_Image[3], absolute_y_val(49));
    lv_obj_set_align(ui_Image[3], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image[3], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[3], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 320);
    lv_obj_set_height(ui_Container[TabPage_cout], 30);
    lv_obj_set_x(ui_Container[TabPage_cout], absolute_x_val(0));
    lv_obj_set_y(ui_Container[TabPage_cout], absolute_y_val(194));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Image[27] = lv_img_create(ui_Container[TabPage_cout]);
    lv_img_set_src(ui_Image[27], &Frame_swipe);
    lv_obj_set_width(ui_Image[27], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[27], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[27], 0);
    lv_obj_set_y(ui_Image[27], 0);
    lv_obj_set_align(ui_Image[27], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[27], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[27], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Image[28] = lv_img_create(ui_Container[TabPage_cout]);
    lv_img_set_src(ui_Image[28], &Frame_swipe);
    lv_obj_set_width(ui_Image[28], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[28], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[28], 320);
    lv_obj_set_y(ui_Image[28], 0);
    lv_obj_set_align(ui_Image[28], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[28], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[28], LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    animate_move_x(ui_Image[27], 0, -320, 10000);
    // animate_move_x(ui_Image[28], 320, 0, 10000);

    TabPage_cout             = 1;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox4 = lv_checkbox_create(ui_Container[TabPage_cout]);
    lv_checkbox_set_text(ui_Checkbox4, "");
    lv_obj_set_width(ui_Checkbox4, 24);   /// 1
    lv_obj_set_height(ui_Checkbox4, 24);  /// 1
    lv_obj_set_x(ui_Checkbox4, absolute_x_val(60) - 35);
    lv_obj_set_y(ui_Checkbox4, absolute_y_val(180));
    lv_obj_add_flag(ui_Checkbox4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_add_state(ui_Checkbox4, LV_STATE_DISABLED);           /// States
    lv_obj_set_align(ui_Checkbox4, LV_ALIGN_TOP_LEFT);

    ui_Checkbox6 = lv_checkbox_create(ui_Container[TabPage_cout]);
    lv_checkbox_set_text(ui_Checkbox6, "");
    lv_obj_set_width(ui_Checkbox6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Checkbox6, absolute_x_val(149) - 19);
    lv_obj_set_y(ui_Checkbox6, absolute_y_val(180));
    lv_obj_add_flag(ui_Checkbox6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_add_state(ui_Checkbox6, LV_STATE_DISABLED);           /// States
    lv_obj_set_align(ui_Checkbox6, LV_ALIGN_TOP_LEFT);

    ui_Checkbox7 = lv_checkbox_create(ui_Container[TabPage_cout]);
    lv_checkbox_set_text(ui_Checkbox7, "");
    lv_obj_set_width(ui_Checkbox7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Checkbox7, absolute_x_val(238) - 3);
    lv_obj_set_y(ui_Checkbox7, absolute_y_val(180));
    lv_obj_add_flag(ui_Checkbox7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_add_state(ui_Checkbox7, LV_STATE_DISABLED);           /// States
    lv_obj_set_align(ui_Checkbox7, LV_ALIGN_TOP_LEFT);

    ui_Image[5] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_Image[5], &C_to_select_checkbox);
    lv_obj_set_width(ui_Image[5], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[5], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[5], 58 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Image[5], 134 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Image[5], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image[5], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[5], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Button[0] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[0], 142);
    lv_obj_set_height(ui_Button[0], 38);
    lv_obj_set_x(ui_Button[0], 89);
    lv_obj_set_y(ui_Button[0], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[0], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[0], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[0], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[0], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[0], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[0], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[0], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[0], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[0], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[6] = lv_img_create(ui_Button[0]);
    lv_img_set_src(ui_Image[6], &Touch_Test);
    lv_obj_set_width(ui_Image[6], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[6], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[6], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[6], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[6], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 2;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[18] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_Image[18],
        &Click_LCD_TEST_button_to_start_screen_test_Red____Green____Blue____White);
    lv_obj_set_width(ui_Image[18], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[18], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[18], 43 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Image[18], 143 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Image[18], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image[18], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[18], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Button[1] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[1], 142);
    lv_obj_set_height(ui_Button[1], 38);
    lv_obj_set_x(ui_Button[1], 89);
    lv_obj_set_y(ui_Button[1], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[1], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[1], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[1], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[1], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[1], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[1], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[1], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[1], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[1], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button[1], ui_event_test_lcd, LV_EVENT_ALL, NULL);

    ui_Image[7] = lv_img_create(ui_Button[1]);
    lv_img_set_src(ui_Image[7], &LCD_Test);
    lv_obj_set_width(ui_Image[7], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[7], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[7], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[7], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[7], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 3;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[19] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_Image[19],
        &O_test_IO_on_the_MBus_will_toggle_between_high_and_low_states_every_1_second);
    lv_obj_set_width(ui_Image[19], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[19], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[19], 46 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Image[19], 134 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Image[19], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image[19], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[19], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Button[2] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[2], 142);
    lv_obj_set_height(ui_Button[2], 38);
    lv_obj_set_x(ui_Button[2], 89);
    lv_obj_set_y(ui_Button[2], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[2], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[2], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[2], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[2], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[2], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[2], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[2], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[2], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[2], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[8] = lv_img_create(ui_Button[2]);
    lv_img_set_src(ui_Image[8], &O_Test);
    lv_obj_set_width(ui_Image[8], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[8], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[8], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[8], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[8], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 4;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea485[0] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextArea485[0], 90);
    lv_obj_set_height(ui_TextArea485[0], 100);
    lv_obj_set_x(ui_TextArea485[0], 23);
    lv_obj_set_y(ui_TextArea485[0], 108 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea485[0], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextArea485[0], "0x01\n0x02\n0x03\n0x04");
    lv_textarea_set_placeholder_text(ui_TextArea485[0], "Placeholder...");

    ui_TextArea485[1] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextArea485[1], 90);
    lv_obj_set_height(ui_TextArea485[1], 100);
    lv_obj_set_x(ui_TextArea485[1], 208);
    lv_obj_set_y(ui_TextArea485[1], 108 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea485[1], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextArea485[1], "0x01\n0x02\n0x03\n0x04");
    lv_textarea_set_placeholder_text(ui_TextArea485[1], "Placeholder...");

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_TextArea[TabPage_cout],
        &Connect_RS485_and_UARTthen_click_RS485_TEST_button_to_start_test);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 119 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 129 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_TextArea[TabPage_cout], &RS485_Recv);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 36 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 209 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_TextArea[TabPage_cout], &UART_Recv);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 223 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 208 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Button[3] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[3], 142);
    lv_obj_set_height(ui_Button[3], 38);
    lv_obj_set_x(ui_Button[3], 89);
    lv_obj_set_y(ui_Button[3], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[3], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[3], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[3], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[3], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[3], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[3], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[3], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[3], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[3], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[9] = lv_img_create(ui_Button[3]);
    lv_img_set_src(ui_Image[9], &RS485_Test);
    lv_obj_set_width(ui_Image[9], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[9], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[9], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[9], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[9], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 5;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreacan[0] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextAreacan[0], 96);
    lv_obj_set_height(ui_TextAreacan[0], 100);
    lv_obj_set_x(ui_TextAreacan[0], 20);
    lv_obj_set_y(ui_TextAreacan[0], 108 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextAreacan[0], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextAreacan[0], "0x01\n0x02\n0x03\n0x04");
    lv_textarea_set_placeholder_text(ui_TextAreacan[0], "Placeholder...");

    ui_TextAreacan[1] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextAreacan[1], 95);
    lv_obj_set_height(ui_TextAreacan[1], 100);
    lv_obj_set_x(ui_TextAreacan[1], 205);
    lv_obj_set_y(ui_TextAreacan[1], 108 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextAreacan[1], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextAreacan[1], "0x01\n0x02\n0x03\n0x04");
    lv_textarea_set_placeholder_text(ui_TextAreacan[1], "Placeholder...");

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_TextArea[TabPage_cout],
        &Connect_the_2_CAN_interfacesthen_click_CAN_TEST_button_to_start_test);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 119 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 129 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_TextArea[TabPage_cout], &CAN0_Recv);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 36 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 209 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_TextArea[TabPage_cout], &CAN1_Recv);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 223 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 208 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Button[4] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[4], 142);
    lv_obj_set_height(ui_Button[4], 38);
    lv_obj_set_x(ui_Button[4], 89);
    lv_obj_set_y(ui_Button[4], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[4], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[4], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[4], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[4], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[4], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[4], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[4], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[4], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[4], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[10] = lv_img_create(ui_Button[4]);
    lv_img_set_src(ui_Image[10], &CAN_Test);
    lv_obj_set_width(ui_Image[10], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[10], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[10], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[10], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[10], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 6;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_TextArea[TabPage_cout],
        &Connect_network_cable_then_click_Ethernet_TEST_to_start_test);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 46 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 174 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextArea[TabPage_cout], 253);
    lv_obj_set_height(ui_TextArea[TabPage_cout], 65);
    lv_obj_set_x(ui_TextArea[TabPage_cout], 33);
    lv_obj_set_y(ui_TextArea[TabPage_cout], 105 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextArea[TabPage_cout],
    //                      "get eth0 ip:192.168.31.21\nget eth1
    //                      ip:192.168.31.22\neth check success! or eth check
    //                      faile!");
    lv_textarea_set_placeholder_text(ui_TextArea[TabPage_cout],
                                     "Placeholder...");

    ui_Button[5] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[5], 142);
    lv_obj_set_height(ui_Button[5], 38);
    lv_obj_set_x(ui_Button[5], 89);
    lv_obj_set_y(ui_Button[5], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[5], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[5], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[5], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[5], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[5], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[5], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[5], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[5], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[5], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[11] = lv_img_create(ui_Button[5]);
    lv_img_set_src(ui_Image[11], &Ethernet_Test);
    lv_obj_set_width(ui_Image[11], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[11], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[11], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[11], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[11], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 7;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_TextArea[TabPage_cout],
                   &Click_I2C_TEST_button_and_scan_port_I2C_devices);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 46 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 190 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextArea[TabPage_cout], 253);
    lv_obj_set_height(ui_TextArea[TabPage_cout], 79);
    lv_obj_set_x(ui_TextArea[TabPage_cout], 33);
    lv_obj_set_y(ui_TextArea[TabPage_cout], 105 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextArea[TabPage_cout],
    //                      "i2cscan...\nget dev 1 : 0x08\ni2c check success! or
    //                      i2c check faile!");
    lv_textarea_set_placeholder_text(ui_TextArea[TabPage_cout],
                                     "Placeholder...");

    ui_Button[6] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[6], 142);
    lv_obj_set_height(ui_Button[6], 38);
    lv_obj_set_x(ui_Button[6], 89);
    lv_obj_set_y(ui_Button[6], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[6], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[6], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[6], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[6], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[6], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[6], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[6], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[6], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[6], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[12] = lv_img_create(ui_Button[6]);
    lv_img_set_src(ui_Image[12], &I2C_Test);
    lv_obj_set_width(ui_Image[12], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[12], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[12], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[12], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[12], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 8;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_TextArea[TabPage_cout],
                   &Click_USB_TEST_button_to_list_all_USB_devices);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 46 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 194 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_TextArea[TabPage_cout] = lv_textarea_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_TextArea[TabPage_cout], 253);
    lv_obj_set_height(ui_TextArea[TabPage_cout], 79);
    lv_obj_set_x(ui_TextArea[TabPage_cout], 33);
    lv_obj_set_y(ui_TextArea[TabPage_cout], 107 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    // lv_textarea_set_text(ui_TextArea[TabPage_cout],
    //                      "lsusb...\nusb check success! or usb check faile!");
    lv_textarea_set_placeholder_text(ui_TextArea[TabPage_cout],
                                     "Placeholder...");

    ui_Button[7] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[7], 142);
    lv_obj_set_height(ui_Button[7], 38);
    lv_obj_set_x(ui_Button[7], 89);
    lv_obj_set_y(ui_Button[7], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[7], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[7], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[7], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[7], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[7], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[7], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[7], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[7], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[7], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[13] = lv_img_create(ui_Button[7]);
    lv_img_set_src(ui_Image[13], &USB_Test);
    lv_obj_set_width(ui_Image[13], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[13], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[13], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[13], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[13], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 9;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea[TabPage_cout] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_TextArea[TabPage_cout],
        &Click__SPEAKER_TEST__button_to_play_audio_and_test_the_speaker);
    lv_obj_set_width(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TextArea[TabPage_cout], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_TextArea[TabPage_cout], 46 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_TextArea[TabPage_cout], 143 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_TextArea[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_TextArea[TabPage_cout],
                    LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_TextArea[TabPage_cout],
                      LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Button[10] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[10], 142);
    lv_obj_set_height(ui_Button[10], 38);
    lv_obj_set_x(ui_Button[10], 89);
    lv_obj_set_y(ui_Button[10], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[10], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[10], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[10], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[10], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[10], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[10], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[10], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[10], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[10], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[16] = lv_img_create(ui_Button[10]);
    lv_img_set_src(ui_Image[16], &Speaker_Test);
    lv_obj_set_width(ui_Image[16], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[16], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[16], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[16], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[16], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 10;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_Button[11] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[11], 142);
    lv_obj_set_height(ui_Button[11], 38);
    lv_obj_set_x(ui_Button[11], 89);
    lv_obj_set_y(ui_Button[11], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[11], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[11], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[11], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[11], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[11], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[11], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[11], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[11], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[11], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[17] = lv_img_create(ui_Button[11]);
    lv_img_set_src(ui_Image[17], &CPU_LOAD_Test);
    lv_obj_set_width(ui_Image[17], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[17], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[17], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[17], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[17], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    ui_Image[17] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(ui_Image[17],
                   &Click__CPU_LOAD_Test__button_to_CPU_load_maximization_test);
    lv_obj_set_width(ui_Image[17], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[17], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[17], 46);
    lv_obj_set_y(ui_Image[17], 143 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Image[17], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image[17], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[17], LV_OBJ_FLAG_SCROLLABLE);  /// Flags

    TabPage_cout             = 11;
    ui_TabPage[TabPage_cout] = lv_tileview_add_tile(
        ui_Tileview1, TabPage_cout, 0, LV_DIR_RIGHT | LV_DIR_LEFT);

    ui_Container[TabPage_cout] = lv_obj_create(ui_TabPage[TabPage_cout]);
    lv_obj_remove_style_all(ui_Container[TabPage_cout]);
    lv_obj_set_width(ui_Container[TabPage_cout], 280);
    lv_obj_set_height(ui_Container[TabPage_cout], 180);
    lv_obj_set_x(ui_Container[TabPage_cout], 20 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Container[TabPage_cout], 44 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Container[TabPage_cout], LV_ALIGN_TOP_LEFT);
    lv_obj_clear_flag(
        ui_Container[TabPage_cout],
        LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_radius(ui_Container[TabPage_cout], 10,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container[TabPage_cout],
                              lv_color_hex(0xD9D9D9),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container[TabPage_cout], 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[26] = lv_img_create(ui_TabPage[TabPage_cout]);
    lv_img_set_src(
        ui_Image[26],
        &Click_RTC_button_to_power_off_the_device_it_will_restart_within_30_seconds);
    lv_obj_set_width(ui_Image[26], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[26], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_x(ui_Image[26], 46 - lv_obj_get_x(ui_Tileview1));
    lv_obj_set_y(ui_Image[26], 138 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Image[26], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Image[26], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[26], LV_OBJ_FLAG_SCROLLABLE);  /// Flags


    ui_Button[9] = lv_btn_create(ui_TabPage[TabPage_cout]);
    lv_obj_set_width(ui_Button[9], 142);
    lv_obj_set_height(ui_Button[9], 38);
    lv_obj_set_x(ui_Button[9], 89);
    lv_obj_set_y(ui_Button[9], 60 - lv_obj_get_y(ui_Tileview1));
    lv_obj_set_align(ui_Button[9], LV_ALIGN_TOP_LEFT);
    lv_obj_add_flag(ui_Button[9], LV_OBJ_FLAG_SCROLL_ON_FOCUS);  /// Flags
    lv_obj_clear_flag(ui_Button[9], LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_radius(ui_Button[9], 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button[9], lv_color_hex(0x3B93EE),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button[9], 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button[9], 0,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Button[9], 0,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Button[9], 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image[15] = lv_img_create(ui_Button[9]);
    lv_img_set_src(ui_Image[15], &RTC_Test);
    lv_obj_set_width(ui_Image[15], LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image[15], LV_SIZE_CONTENT);  /// 1
    lv_obj_set_align(ui_Image[15], LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image[15], LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
    lv_obj_clear_flag(ui_Image[15], LV_OBJ_FLAG_SCROLLABLE);  /// Flags


    lv_obj_add_event_cb(ui_Tileview1, ui_event_Tileview1, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Button[2], ui_event_test_bus, LV_EVENT_ALL, NULL);

    lv_obj_add_event_cb(ui_Button[7], screen_test_usb_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[4], screen_test_can_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[5], screen_test_eth_event, LV_EVENT_CLICKED,
                        NULL);
    lv_obj_add_event_cb(ui_Button[9], screen_test_rtc_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[10], screen_test_play_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[0], screen_test_touch_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[6], screen_test_i2c_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[3], screen_test_rs485_event, LV_EVENT_CLICKED,
                        NULL);

    lv_obj_add_event_cb(ui_Button[11], screen_test_cpu_event, LV_EVENT_CLICKED,
                        NULL);

    for (int i = 0; i < FUN_NUMBER; i++) {
        led[i] = lv_led_create(ui_Screen1);
        lv_obj_set_width(led[i], 8);   /// 1
        lv_obj_set_height(led[i], 8);  /// 1
        lv_obj_set_x(led[i], 50 + 20 * i);
        lv_obj_set_y(led[i], 230);
        lv_led_set_color(led[i], lv_color_hex(0xADABEF));

        lv_obj_set_align(led[i], LV_ALIGN_TOP_LEFT);
        lv_led_off(led[i]);
    }
    lv_led_on(led[0]);
}

void ui_Screen2_screen_init(void) {
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen_lcd, LV_EVENT_ALL, NULL);
}
void ui_Screen3_screen_init(void) {
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0xFF00),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen_lcd, LV_EVENT_ALL, NULL);
}
void ui_Screen4_screen_init(void) {
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);  /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0xFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen_lcd, LV_EVENT_ALL, NULL);
}
void ui_Screen_void_screen_init(void) { ui_Screenvoid = lv_obj_create(NULL); }