
CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"
CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
CONFIG_LVGL_COMPONENT_ENABLED=y
CONFIG_LVGL_COMPONENT_LVGL=y
CONFIG_LVGL_COMPONENT_LV_DRIVERS=y
CONFIG_DEVICE_DRIVER_ENABLED=y
CONFIG_DEVICE_I2C_ENABLED=y
CONFIG_DEVICE_UART_ENABLED=y
CONFIG_LHV_ENABLED=y
CONFIG_LHV_WITH_EVPP=y

