CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"
# CONFIG_COMPONENT1_ENABLED=y
CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
CONFIG_TOOLCHAIN_FLAGS="-mcpu=cortex-a7 -mfpu=neon-vfpv4"
CONFIG_UTILITIES_ENABLED=y
CONFIG_MINICV2_COMPONENT_ENABLED=y
CONFIG_DEVICE_DRIVER_ENABLED=y
CONFIG_DEVICE_FRAMEBUFFER_ENABLED=y