# component/SConscript
Import("env")
import os

with open(env["PROJECT_TOOL_S"]) as f:
    exec(f.read())


def get_sqlite3_lib():
    sqlite3_path = check_wget_down(
        "https://sqlite.org/2024/sqlite-amalgamation-3460000.zip",
        "sqlite-amalgamation-3460000.zip",
    )
    sqlite3_project_path = os.path.join(sqlite3_path, "sqlite-amalgamation-3460000")
    INCLUDE = [sqlite3_project_path]
    SRCS = [os.path.join(sqlite3_project_path, "sqlite3.c")]
    return INCLUDE, SRCS


if "CONFIG_SQLITE3_COMPOENENT_ENABLED" in os.environ:
    SRCS = []
    INCLUDE = []
    PRIVATE_INCLUDE = []
    REQUIREMENTS = []
    STATIC_LIB = []
    DYNAMIC_LIB = []
    DEFINITIONS = []
    DEFINITIONS_PRIVATE = []
    LDFLAGS = []
    LINK_SEARCH_PATH = []
    _INCLUDE, _SRCS = get_sqlite3_lib()
    INCLUDE += _INCLUDE
    SRCS += _SRCS

    env["COMPONENTS"].append(
        {
            "target": os.path.basename(env["component_dir"]),
            "SRCS": SRCS,
            "INCLUDE": INCLUDE,
            "PRIVATE_INCLUDE": PRIVATE_INCLUDE,
            "REQUIREMENTS": REQUIREMENTS,
            "STATIC_LIB": STATIC_LIB,
            "DYNAMIC_LIB": DYNAMIC_LIB,
            "DEFINITIONS": DEFINITIONS,
            "DEFINITIONS_PRIVATE": DEFINITIONS_PRIVATE,
            "LDFLAGS": LDFLAGS,
            "LINK_SEARCH_PATH": LINK_SEARCH_PATH,
            "REGISTER": "static",
        }
    )
