# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())


def get_opencv_from_axera():
    opencv_path = str(ADir('../../github_source/opencv-arm-linux'))
    if not os.path.exists(opencv_path):
        zip_file = str(AFile('../../github_source/opencv-arm-linux-gnueabihf-gcc-7.5.0.zip'))
        zip_file_extrpath = opencv_path + '_tmp'
        down_url = "https://github.com/AXERA-TECH/ax-samples/releases/download/v0.1/opencv-arm-linux-gnueabihf-gcc-7.5.0.zip"
        
        if 'CONFIG_REPO_AUTOMATION' in os.environ:
            down = 'y'
        else:
            down = input('{} does not exist. Please choose whether to download it automatically? Y/N :'.format('opencv-mobile-2.4.13.7-armlinux'))
            down = down.lower()
        if down == 'y':
            # from git import Repo
            import requests
            import parse
            import zipfile
            import shutil
            try:
                # Downloading via HTTP (more common)
                if not os.path.exists(zip_file):
                    response = requests.get(down_url)
                    if response.status_code == 200:
                        with open(zip_file, 'wb') as file:
                            file.write(response.content)
                    else:
                        env.Fatal("{} down failed".format(down_url))
                with zipfile.ZipFile(zip_file, 'r') as zip_ref:
                    zip_ref.extractall(zip_file_extrpath)
                shutil.move(os.path.join(zip_file_extrpath, 'opencv-arm-linux'), opencv_path)
                shutil.rmtree(zip_file_extrpath)
                print("The {} download successful.".format(down_url))
            except Exception as e:
                print('Please manually download {} to {} .'.format(down_url, zip_file))
                env.Fatal("Cloning failed.: {}".format(e))
        else:
            env.Fatal('Please manually download {} to {} .'.format(down_url, zip_file))
    INCLUDE = [os.path.join(opencv_path, 'include/opencv4')]
    STATIC_LIB = AGlob(os.path.join('../../github_source/opencv-arm-linux', 'lib/*.a'))
    STATIC_LIB += AGlob(os.path.join('../../github_source/opencv-arm-linux', 'lib/opencv4/3rdparty/*.a'))
    return INCLUDE, STATIC_LIB

def get_opencv_from_ncnn():
    opencv_path = str(ADir('../../github_source/opencv-mobile-2.4.13.7-armlinux'))
    if not os.path.exists(opencv_path):
        zip_file = opencv_path + '.zip'
        zip_file_extrpath = opencv_path + '_tmp'
        down_url = "https://github.com/nihui/opencv-mobile/releases/download/v26/opencv-mobile-2.4.13.7-armlinux.zip"
        
        if 'CONFIG_REPO_AUTOMATION' in os.environ:
            down = 'y'
        else:
            down = input('{} does not exist. Please choose whether to download it automatically? Y/N :'.format('opencv-mobile-2.4.13.7-armlinux'))
            down = down.lower()
        if down == 'y':
            # from git import Repo
            import requests
            import parse
            import zipfile
            import shutil
            try:
                # Downloading via HTTP (more common)
                if not os.path.exists(zip_file):
                    response = requests.get(down_url)
                    if response.status_code == 200:
                        with open(zip_file, 'wb') as file:
                            file.write(response.content)
                    else:
                        env.Fatal("{} down failed".format(down_url))
                with zipfile.ZipFile(zip_file, 'r') as zip_ref:
                    zip_ref.extractall(zip_file_extrpath)
                shutil.move(os.path.join(zip_file_extrpath, 'opencv-mobile-2.4.13.7-armlinux'), opencv_path)
                shutil.rmtree(zip_file_extrpath)
                print("The {} download successful.".format(down_url))
            except Exception as e:
                print('Please manually download {} to {} .'.format(down_url, zip_file))
                env.Fatal("Cloning failed.: {}".format(e))
        else:
            env.Fatal('Please manually download {} to {} .'.format(down_url, zip_file))
    
    gcc_dumpmachine = env['GCC_DUMPMACHINE']
    INCLUDE = [os.path.join(opencv_path, gcc_dumpmachine, 'include')]
    STATIC_LIB = AGlob(os.path.join('../../github_source/opencv-mobile-2.4.13.7-armlinux', gcc_dumpmachine, 'lib/*.a'))
    return INCLUDE, STATIC_LIB

if 'CONFIG_STATIC_PACKAGE_ENABLED' in os.environ:
    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[]
    REQUIREMENTS=[]
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=[]
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]

    if 'CONFIG_OPENCV_LIB_AXERA_ENABLED' in os.environ:
        inc, slib = get_opencv_from_axera()
        INCLUDE += inc
        STATIC_LIB += slib + slib

    if 'CONFIG_OPENCV_LIB_NCNN_ENABLED' in os.environ:
        inc, slib = get_opencv_from_ncnn()
        INCLUDE += inc
        STATIC_LIB += slib + slib

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'static'
                            })
