# unix
# CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"
# win
# CONFIG_TOOLCHAIN_PATH="..\\gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf\\bin"

# CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
CONFIG_MBEDTLS_COMPONENT_ENABLED=y
CONFIG_EVEREST_ENABLED=y
CONFIG_P256M_ENABLED=y
CONFIG_MBEDCRYPTO_ENABLED=y
CONFIG_MBEDX509_ENABLED=y
CONFIG_MBEDTLS_ENABLED=y