# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())



if 'CONFIG_LVGL_COMPONENT_ENABLED' in os.environ:
    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[]
    REQUIREMENTS=[]
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=[]
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]
    INCLUDE.append(ADir('include'))
    INCLUDE.append(ADir('../../github_source/lvgl'))
    if 'CONFIG_LVGL_COMPONENT_LVGL' in os.environ:
        SRCS += append_srcs_dir([ADir('../../github_source/lvgl/lvgl/src'), 
                                 ADir('../../github_source/lvgl/lvgl/demos'),
                                 ADir('../../github_source/lvgl/lvgl/examples')])
    if 'CONFIG_LVGL_COMPONENT_LV_DRIVERS' in os.environ:
        SRCS += append_srcs_dir([ADir('../../github_source/lvgl/lv_drivers')])

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'static'
                            })
