# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())


if 'CONFIG_TINYALSA_COMPONENT_ENABLED' in os.environ:
    check_component('tinyalsa')
    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[]
    REQUIREMENTS=[]
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=[]
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]
    INCLUDE.append(ADir('../../github_source/tinyalsa/src'))
    INCLUDE.append(ADir('../../github_source/tinyalsa/include'))
    SRCS += AGlob('../../github_source/tinyalsa/src/*.c*')
    DEFINITIONS_PRIVATE += ['-Wall' ,'-Wextra' ,'-Werror' ,'-Wfatal-errors']

    REQUIREMENTS += ['dl']

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'shared' if 'CONFIG_TINYALSA_COMPONENT_DYNAMIC' in os.environ else 'static'
                            })
