# component2/SConscript
Import('env')
import os
with open(env['PROJECT_TOOL_S']) as f:
    exec(f.read())


if 'CONFIG_HTTP_PARSER_ENABLED' in os.environ:
    file_path = check_component('http-parser')
    SRCS=[]
    INCLUDE=[]
    PRIVATE_INCLUDE=[ADir('.')]
    REQUIREMENTS=[]
    STATIC_LIB=[]
    DYNAMIC_LIB=[]
    DEFINITIONS=[]
    DEFINITIONS_PRIVATE=['-DHTTP_PARSER_STRICT=1', '-O3']
    LDFLAGS=[]
    LINK_SEARCH_PATH=[]

    INCLUDE.append(os.path.join(env['GIT_REPO_LISTS']['http-parser']['path']))
    SRCS += [os.path.join(env['GIT_REPO_LISTS']['http-parser']['path'], 'http_parser.c')]

    env['COMPONENTS'].append({'target':os.path.basename(env['component_dir']),
                            'SRCS':SRCS,
                            'INCLUDE':INCLUDE,
                            'PRIVATE_INCLUDE':PRIVATE_INCLUDE,
                            'REQUIREMENTS':REQUIREMENTS,
                            'STATIC_LIB':STATIC_LIB,
                            'DYNAMIC_LIB':DYNAMIC_LIB,
                            'DEFINITIONS':DEFINITIONS,
                            'DEFINITIONS_PRIVATE':DEFINITIONS_PRIVATE,
                            'LDFLAGS':LDFLAGS,
                            'LINK_SEARCH_PATH':LINK_SEARCH_PATH,
                            'REGISTER':'shared' if 'CONFIG_LHV_DYNAMIC' in os.environ else 'static'
                            })