
# CONFIG_COMPONENT1_ENABLED=y
CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf/bin"
CONFIG_TOOLCHAIN_PREFIX="arm-linux-gnueabihf-"
CONFIG_STATIC_PACKAGE_ENABLED=y
CONFIG_GRPC_LIB_ENABLED=y