// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_start_ui

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif
uint64_t p___millis(void);


void screen_switch_event(lv_event_t * e);
void screen_test_bus_event(lv_event_t * e);
void screen_test_usb_event(lv_event_t *e);
void screen_test_can_event(lv_event_t *e);
void screen_test_rs485_event(lv_event_t *e);
void screen_test_i2c_event(lv_event_t *e);
void screen_test_eth_event(lv_event_t *e);
void screen_test_rtc_event(lv_event_t *e);
void screen_test_play_event(lv_event_t *e);
void screen_test_touch_event(lv_event_t *e);
void screen_test_cpu_event(lv_event_t *e);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
