// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: core135_start_ui

#ifndef _UI_COMP_BUTTON1_H
#define _UI_COMP_BUTTON1_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button1
#define UI_COMP_BUTTON1_BUTTON1 0
#define _UI_COMP_BUTTON1_NUM 1
lv_obj_t * ui_Button1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
