import os
Import('env')
now_dir = env['component_dir']


env['component_dir'] = os.path.join(now_dir, 'sys')
SConscript('sys/SConstruct', exports='env')

env['component_dir'] = os.path.join(now_dir, 'vdec')
SConscript('vdec/SConstruct', exports='env')

env['component_dir'] = os.path.join(now_dir, 'venc')
SConscript('venc/SConstruct', exports='env')

env['component_dir'] = os.path.join(now_dir, 'test')
SConscript('test/SConstruct', exports='env')

















