
CONFIG_TOOLCHAIN_PATH="/opt/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin"
CONFIG_TOOLCHAIN_PREFIX="aarch64-linux-gnu-"
CONFIG_LVGL_COMPONENT_ENABLED=y
CONFIG_LVGL_COMPONENT_LVGL=y
CONFIG_LVGL_COMPONENT_LV_DRIVERS=y